version: "3.9"

services:
  phutungotoquyba-be:
    image: phutungotoquyba-be:1.0.0
    container_name: phutungotoquyba-be
    restart: always
    # environment:
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - phutungotoquyba-db

  phutungotoquyba-fe:
    image: phutungotoquyba-fe:1.0.0
    container_name: phutungotoquyba-fe
    restart: always
    env_file:
      - .env.fe.production
    ports:
      - "3000:3000"

  phutungotoquyba-db:
    image: postgres:15
    container_name: phutungotoquyba-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: phutungotoquyba
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data